token_check_box_for_login = "token_button"
token_edit_box = "token"
login_btn = "//*[@text='LOGIN']"
go_to_login_menu_button="//*[@text='LOGIN']"
main_page_title_xpath = "//*[@text='News Feed']"
side_menu_btn = "//*[@id='toolbar']/android.widget.ImageButton[@contentDescription='Navigate up']"
search_in_side_menu = "//*[@text='Search']"
profile_in_side_menu_btn = "switcher"
side_menu_logout_btn = "//*[@text='Logout']"
search_edit_text = "search_src_text"#//*[@id='search_src_text']
issues_row_in_project = "issues_row"
issue_labales_locator = "tv_desc"
comment_on_issue_edit_text = "et_basic_editor"
send_comment_btn = "send_button"
comment_text_id = "tv_desc"
add_issue_btn = "fab_add"
new_issue_titile="et_title"
new_issue_desc = "editor"
add_new_issue_btn = "//*[@resource-id='com.gh4a:id/coordinator_layout']/*[@class='android.widget.ImageButton']"
close_issue = "issue_close"
edit_issue = "edit_fab"
confirm_close_issue = "//*[@text='CLOSE']"
issue_state = "tv_state"

